start winword 
start cmd 
start mspaint  
start notepad
start explorer
start write
start cmd 
start explorer
start notepad
start control
start calc 
start write
start chrome
start notepad
start cmd 
start winword 
start notepad
start control
start write
start cmd 